In [3]:
import numpy as np
a=np.array([1,2,3,4]) # create an array
a+1   # scalar addition, 1 is added to every element of a

array([2, 3, 4, 5])

In [4]:
a**2

array([ 1,  4,  9, 16])

In [5]:
b=np.ones(4)+1
a-b


array([-1.,  0.,  1.,  2.])

In [6]:
a*b

array([2., 4., 6., 8.])

In [11]:
# matrix  multiplication
c=np.diag([1,2,3,4])
print(c * c)
print("***************")
print(c.dot(c))  # same as c*c

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [12]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b

array([False,  True, False,  True])

In [13]:
a>b

array([False, False,  True, False])

In [15]:
# array wise comparisons
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

np.array_equal(a,b)

False

In [17]:
np.array_equal(a,c)

True

In [19]:
# logical operations
a=np.array([1,1,0,0] ,dtype=bool)
b=np.array([1,0,1,0] ,dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [20]:
np.logical_and(a,b)

array([ True, False, False, False])

In [21]:
# transcendental functions:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [22]:
np.log(a)

<ipython-input-22-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [24]:
np.exp(a)  # evaluates e*x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [26]:
''' shape mismatch
a=np.arange(4)
a+np.array([1,2])
'''  #operands could not be broadcast together with shapes (4,) (2,)

' shape mismatch\na=np.arange(4)\na+np.array([1,2])\n'

In [27]:
# basic reductions
x=np.array([1,2,3,4])
np.sum(x)

10

In [28]:
# sum by rows and columns
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [29]:
x.sum(axis=0)   # columns first dimension

array([3, 3])

In [30]:
x.sum(axis=1)   # rows first dimension

array([2, 4])

In [33]:
#other reductions
x = np.array([1,3,2])
x.min()


1

In [35]:
x.max()

3

In [37]:
x.argmin() # index of min value

0

In [36]:
x.argmax() # index of max value

1

In [39]:
# logical operations
np.all([True,True,False])

False

In [40]:
np.any([True,True,False])

True

In [41]:
a=np.zeros([50,50])
np.any(a!=0)

False

In [42]:
np.all(a==a)

True

In [44]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

True