In [4]:
# statistics
import numpy as np
x=np.array([1,2,3,2])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

2.0

In [5]:
np.median(x)

2.0

In [7]:
np.median(y, axis=-1)

array([2., 5.])

In [8]:
x.std()

0.7071067811865476

In [13]:
a=np.tile(np.arange(0,40,10),(3,1))
print(a)
print("*************")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [11]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [15]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [16]:
a=np.arange(0,40,10)
a.shape

(4,)

In [18]:
a=a[:,np.newaxis] # adds a new axis --> 2D array
a.shape

(4, 1)

In [17]:
a

array([ 0, 10, 20, 30])

In [19]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [23]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()  # returns a contagious flattened array

array([1, 2, 3, 4, 5, 6])

In [24]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [26]:
# reshaping
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [27]:
b=a.ravel()
print(b)

[1 2 3 4 5 6]


In [28]:
b=b.reshape([2,3])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# shape may also return a copy
a=np.zeros([3,2])
b=a.T.reshape(3*2)
b[0] =50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [2]:
# 2D array will become 3D array
# 3D array will become 4D array
import numpy as np
z=np.array([1,2,3])
z

array([1, 2, 3])

In [16]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [6]:
a=np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [7]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [9]:
a[0,2,1]

5

In [10]:
# resizing
a= np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [12]:
# sorting along an axis
a=np.array([[5,4,6],[2,3,2]])
b= np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [13]:
# in-plane sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [14]:
#sorting with fancy indexing
a=np.array([4,3,1,2])
j=np.argsort(a)
j

array([2, 3, 1, 0])

In [15]:
a[j]

array([1, 2, 3, 4])