In [8]:
import numpy as np
a = np.array([0, 1, 2])
print(a)
print(np.arange(10))

[0 1 2]
[0 1 2 3 4 5 6 7 8 9]


In [1]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

507 µs ± 50.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:

import numpy as np
a = np.arange(1000)  # creating numpy array
%timeit a**2    #numpy is memory efficiient as well as it provides fast operation


1.44 µs ± 382 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [12]:
#1-D
a = np.array([0,1,2,3,4])


# print dimensions
a.ndim

#shape
a.shape


len(a)

5

In [15]:
#2-D, 3-D
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [18]:
len(b)  #returns the size of first dimension

2

In [20]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
c.ndim


3

In [23]:
c.shape

(2, 2, 2)

In [25]:
#functions for creating arrays
a = np.arange(1,10,2 )#start, end(exclusive) , step
a

array([1, 3, 5, 7, 9])

In [26]:
#common array
a=np.ones((3,3))    #function argumennts ; 3 rows and 3 columns
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
# identity matrix ; returns a 2D array with ones on the diagonal and zeros elsewhere
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.eye(3,2) # 3 is no. of rows; 2 is no. of columns

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [27]:
# using linear space
a=np.linspace(0,1,6) # start, end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# create array using diagonal function

a= np.diag([1,2,3,4])
a # construct a 2-D diagonal array

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [8]:
np.diag(a) # extract diagonal

array([1, 2, 3, 4])

In [9]:
# create array using random
a=np.random.rand(4)
a

array([0.86619646, 0.24578516, 0.56227487, 0.96588725])

In [10]:
a= np.random.randn(4) # standard normal variant
a

array([ 0.40721904,  0.22910139, -1.92074704,  2.09208308])

In [13]:
# basic datatypes
a= np.arange(10)
a.dtype

dtype('int64')

In [15]:
# we can explicitly specify which data type you want
a=np.arange(10, dtype="float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
# default datatype if float for zeros and ones function
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [18]:
d= np.array([1+2j , 2+4j]) # complex datatype
print(d.dtype)

complex128


In [20]:
b=np.array([True,False,True,False])  # boolean datatype
print(b.dtype)

bool


In [22]:
s=np.array(['Qurat','Aisha','Insha'])
s.dtype

dtype('<U5')

In [23]:
a=np.arange(10)
print(a[5]) # indices begin at 0

5


In [24]:
# for multidimentional arrays, indexes are tuples of integers
a = np.diag([1,2,3])
print(a[2,2])

3


In [26]:
a[2,1] =5  #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [27]:
# slicing
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a[1:8:2]  # startindex, endindex(exclusive) , step

array([1, 3, 5, 7])

In [29]:
# combining sklicing and asssignment;
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [34]:
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [36]:
#copies and views
a=np.arange(10)
a
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [37]:
np.shares_memory(a,b) # two variables sharing the same memory

True

In [38]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [40]:
a=np.arange(10)
c=a[::2].copy()   # force a copy
c

array([0, 2, 4, 6, 8])

In [41]:
a =np.random.randint(0,20,15)
a

array([15, 17,  8,  2, 15,  8, 11,  0, 17, 11,  5, 17,  8, 15, 15])

In [42]:
# using boolean mask
mask=(a%2==0)
extract_from_a = a[mask]
extract_from_a

array([8, 2, 8, 0, 8])

In [43]:
a[mask]=-1
a

array([15, 17, -1, -1, 15, -1, 11, -1, 17, 11,  5, 17, -1, 15, 15])

In [46]:
# indexing with array of integer
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [48]:
# new values can be assigned
a[[9,7]]= -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])